"""initialize

Revision ID: 049dc9ed2356
Revises: 
Create Date: 2020-01-16 18:29:35.513800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '049dc9ed2356'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invite_code', sa.String(), nullable=True),
    sa.Column('node_id', sa.String(), nullable=True),
    sa.Column('funding_amount', sa.BigInteger(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invites_invite_code'), 'invites', ['invite_code'], unique=True)
    op.create_index(op.f('ix_invites_is_used'), 'invites', ['is_used'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invites_is_used'), table_name='invites')
    op.drop_index(op.f('ix_invites_invite_code'), table_name='invites')
    op.drop_table('invites')
    # ### end Alembic commands ###
