"""add push amount

Revision ID: 08ba9da075fe
Revises: 049dc9ed2356
Create Date: 2020-01-17 12:08:29.932811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08ba9da075fe'
down_revision = '049dc9ed2356'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invites', sa.Column('push_amount', sa.BigInteger(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invites', 'push_amount')
    # ### end Alembic commands ###
